apiVersion: v1
entries:
  chart-with-cluster-admin-crb:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-12-11T21:01:55.01361803+01:00"
    description: A Helm chart for Kubernetes
    digest: 735487e8cfcbefa69ba4f342277167e5676b9fb6d00866038b3b9ab7e535461e
    name: chart-with-cluster-admin-crb
    type: application
    urls:
    - chart-with-cluster-admin-crb-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-12-11T21:01:55.01346466+01:00"
    description: A Helm chart for Kubernetes
    digest: 7a36736521dc1c2a02b96d1d16ddf1aa32e9e244c62a797a19674aad64f2fa8a
    name: chart-with-cluster-admin-crb
    type: application
    urls:
    - chart-with-cluster-admin-crb-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-12-11T21:01:55.013280624+01:00"
    description: A Helm chart for Kubernetes
    digest: 01612ff6bd298891ec868326cd075284d92795564e658bb6b3f1d9e17d4955b4
    name: chart-with-cluster-admin-crb
    type: application
    urls:
    - chart-with-cluster-admin-crb-0.1.0.tgz
    version: 0.1.0
generated: "2020-12-11T21:01:55.012494603+01:00"
